export const PhraseStore = [
  { text: "Níl ach braon beag fola ort", mood: "serious" },
{ text: "Beidh biseach ort go luath", mood: "optimistic" },
{ text: "Tusa mo bhuachaillín/chailín bán!", mood: "flirtatious" },
{ text: "Curifidh mé plástar ort anois", mood: "threatening" },
{ text: "Tá tú an-chróga", mood: "complimentary" },
{ text: "Faigh scuab agus nigh do chuid fiacla", mood: "directive" },
{ text: "Suas síos", mood: "neutral" },
{ text: "Idir na fiacla", mood: "neutral" },
{ text: "Faigh do chóta agus cuir ort é", mood: "directive" },
{ text: "Tá sé fuar go leor inniu", mood: "neutral" },
{ text: "Déan deifir!", mood: "urgent" },
{ text: "Maidin Mhaith", mood: "friendly" },
{ text: "Ar chodail tú go maith?", mood: "inquiring" },
{ text: "Tá sé in am éirí", mood: "optimistic" },
{ text: "Gabh isteach sa seomra folctha agus nigh tú féin", mood: "directive" },
{ text: "Gheobhaidh mé bosca nua sópa", mood: "optimistic" },
{ text: "Faigh tuáille úr ghlan", mood: "directive" },
{ text: "See on-shin guh foe-ull", mood: "neutral" },
{ text: "Beidh brú ort ansin i gceann cúpla lá", mood: "warning" },
{ text: "Cá bhfuil do Bhosca Lóin?", mood: "inquiring" },
{ text: "Bí cinnte agus do lón ar fad a ithe inniu", mood: "directive" },
{ text: "Ná déan deramad ar do lón!", mood: "warning" },
{ text: "Cuir ort do chóta", mood: "directive" },
{ text: "Is binn béal ina thost", mood: "serious" },
{ text: "Ní hé lá na gaoithe lá na scolb", mood: "philosophical" },
{ text: "Is fearr rith maith ná drochsheasamh", mood: "optimistic" },
{ text: "Eist moran agus can beagan", mood: "directive" },
{ text: "Is minic a gheibhean beal oscailt diog dunta!", mood: "humorous" },
{ text: "De reir a cheile a thogtar na caisleain", mood: "philosophical" },
{ text: "Comhghairdeas", mood: "congratulatory" },
{ text: "Slainte", mood: "congratulatory" },
{ text: "O m'anam", mood: "expressive" },
{ text: "a ghra mo chroi", mood: "romantic" },
{ text: "Saol fada chugat", mood: "hopeful" },
{ text: "Codladh samh", mood: "peaceful" },
{ text: "cuimhnigh i gconai", mood: "reflective" },
{ text: "Is fearr Gaeilge briste, na Bearla cliste", mood: "clever" },
{ text: "Ni tir gan teanga", mood: "proverbial" },
{ text: "Is fhearr fheuchainn na bhith san duil", mood: "wise" },
{ text: "Tada gan iarracht", mood: "defeatist" },
{ text: "Cha d'dhùin doras nach d'fhosgail doras", mood: "determined" },
{ text: "Níl agam ach beagáinín Gaeilge.", mood: "modest" },
{ text: "An miste leat labhairt níos moille?", mood: "inquiring" },
{ text: "Ní thuigim", mood: "perplexed" },
{ text: "an Samhradh, an Fhomhair, an Geimhreadh, an tEarrach", mood: "poetic" },
{ text: "ta se gaofar/fuar/ag cur baisti", mood: "descriptive" },
{ text: "La brea ata ann", mood: "optimistic" },
{ text: "Corp dicheile", mood: "humorous" },
{ text: "Rogha an da dhiogha", mood: "proverbial" },
{ text: "Bua na cainte", mood: "inspiring" },
{ text: "Thar gach ni eile...", mood: "assertive" },
{ text: "Ni mor a admhail....", mood: "proverbial" },
{ text: "Ar an iomlan...", mood: "serious" },
{ text: "Ni mor a admhail...", mood: "proverbial" },
{ text: "Is baolach...", mood: "cautionary" },
{ text: "de reir dealramh", mood: "proverbial" },
{ text: "Ni neart go cur le cheile.", mood: "proverbial" },
{ text: "Nil aon tintean mar do t(h)intean fein.", mood: "proverbial" },
{ text: "Is folamh fuar e teach gan bean.", mood: "proverbial" },
{ text: "Ni lia duine na tuairim", mood: "philosophical" },
{ text: "Ni lia tir na nos", mood: "proverbial" },
{ text: "Is leir don saol e an firinne", mood: "truthful" },
{ text: "Thar gach ni eile", mood: "assertive" },
{ text: "Ni mor a admhail", mood: "proverbial" },
{ text: "Ar an iomlán", mood: "serious" },
{ text: "Maire/Seosaimh bhocht", mood: "sympathetic" },
{ text: "Ta si/se ag caoineadh", mood: "melancholic" },
{ text: "Thit si/se ar an urlar", mood: "humorous" },
{ text: "Ta me/tu go hiontach", mood: "positive" },
{ text: "Ta se/si are buille", mood: "negative" },
{ text: "Ta sinn/sibh/siad tuirseach", mood: "tired" },
{ text: "Ni ceart go cur le cheile", mood: "wise" },
{ text: "Is maith an scathan suil charad", mood: "friendly" },
{ text: "Ni hespa go dith carad", mood: "loyal" },
{ text: "Ta athas/bron/fearg/ocras/tart orm", mood: "emotional" },
{ text: "Ta tu mall/go luath/go halainn/ard/go tapaidh", mood: "descriptive" },
{ text: "Ta se te/fuar/fliuch/tirim amach", mood: "descriptive" },
{ text: "Nil aon leigheas ar an ngra ach posadh", mood: "romantic" },
{ text: "An rud a lionas an tsuil lionann se an croi", mood: "philosophical" },
{ text: "Giorraionn beirt bothar", mood: "humorous" },
{ text: "Ni heolas go haontios!", mood: "curious" },
{ text: "Olann an cat cluin bainne leis!", mood: "humorous" },
{ text: "Conas ata tu?", mood: "casual" },
{ text: "Glacfaidh me do theocht/chuisle", mood: "determined" },
{ text: "Gheobhaidh me an bhanaltra/dochtuir duit.", mood: "hopeful" },
{ text: "Mo seanathair agus seanmathair", mood: "family" },
{ text: "Dearthair, deirfiur, aintín, uncail", mood: "family" },
{ text: "Mathair, athair, mac, inin", mood: "family" },
{ text: "An toigh leat te/cofaidh/bainne ?", mood: "casual" },
{ text: "An gabh thu tuilleadh?", mood: "curious" },
{ text: "Tapadh leat", mood: "grateful" },
{ text: "Gardai! Ta se prainneach.", mood: "emergency" },
{ text: "Taim i gcruachais anois", mood: "troubled" },
{ text: "Chaill me mo mhala.", mood: "regretful" },
{ text: "Gabh mo leithscaal", mood: "apologetic" },
{ text: "Nil Gaeilge maith agam", mood: "apologetic" },
{ text: "An Bhfuil Bearla/Gaeilge agat", mood: "casual" },
{ text: "Ta me i gcruachais.", mood: "troubled" },
{ text: "Ta me ar strae/gortaithe/tinneas", mood: "unwell" },
{ text: "Ba mhaith liom an dochtuir", mood: "needy" },
]
