export const ProverbStore = [
  { text: "Níor líon beannacht bolg riamh. -- A blessing never filled a belly", mood: "wise" },
  { text: "Bíonn blas ar an mbeagán. -- A little of anything is tasty", mood: "neutral" },
  { text: "Beatha duine a thoil -- Everyone to his own tastes", mood: "happy" },
  { text: "Aithnítear cara i gcruatan. -- It is in hardship that a friend is recognised", mood: "happy" },
  { text: "Bíonn caora dhubh ar an tréad is gile -- Even the whitest flock has a black sheep", mood: "neutral" },
  { text: "Galar gan náire an tart. -- Thirst is a shameless disease", mood: "serious" },

  { text: "Más maith leat do mholadh faigh bás: más maith leat do cháineadh pós. -- If you want to be praised, die: if you want to be criticized, marry", mood: "humorous" },

  { text: "Ag duine féin is fearr a fhios cá luíonn an bhróg air. -- A person best knows where the shoe troubles him", mood: "thoughtful" },
  { text: "Aithníonn ciaróg ciaróg eile.  -- It takes one to know one", mood: "humorous" },

  { text: "An gad is giorra don scornach is túisce is ceart a scaoileadh. -- The knot nearest the throat is the the one to release first", mood: "wise" },
  { text: "An lao ite i mbolg na bó. --Don't count your chickens before they're hatched", mood: "humorous" },
  { text: "An luibh ná faightear is í a fhóireann. -- The herb that can't be found is the very one which works", mood: "thoughtful" },
  { text: "An rud a chíonn an leanbh is é a níonn an leanbh. -- What the child sees the child does ", mood: "wise" },
  { text: "An rud a scríobhann an púca, léann sé féin é. -- What the ghost writes, the ghost reads", mood: "warning" },
  { text: "An rud a théann i bhfad téann sé i bhfuaire. -- What goes on for a long time loses its attractiveness", mood: "thoughtful" },
  { text: "An rud is annamh is iontach.", mood: "happy -- What's seldom is wonderful" },
  { text: "An rud is measa le duine ar domhan n’fheadair sé nach é lár a leasa é.", mood: "wise -- The very thing a person dreads most in the world could be the best thing for him" },
  { text: "An rud nach bhfuil leigheas air caithfear cur suas leis. -- What can't be cured must be endured", mood: "thoughtful" },
  { text: "An rud nach féidir ní féidir é. -- The impossible cannot be done", mood: "wise" },
  { text: "An t-uan ag múineadh méilí dá mháthair. -- The lamb teaching its mother how to bleat", mood: "humorous" },
  { text: "An tslat nuair a chruann le haois is deacair í a shníomh ina gad. -- hen the rod hardens with age it's difficult to bend it", mood: "thoughtful" },
  { text: "An té a bhfuil builín aige gheobhaidh sé scian lena ghearradh. -- The man who has a loaf will get a knife to cut it", mood: "humorous" },
  { text: "An té a bhíonn amuigh fuarann a chuid. -- The one who is out, his share gets cold", mood: "wise" },
  { text: "An té a bhíonn siúlach bíonn sé scéalach. -- Travellers have tales", mood: "wise" },
  { text: "An té a bhíonn thuas óltar deoch air. -- When you're up, they drink to you", mood: "happy" },
  { text: "An té a bhíonn thíos buailtear cos air. -- When you're down, they kick you", mood: "unlucky" },
  { text: "An té a dtéann teist na mochóirí amach air ní cás dó codladh go headra. -- The person who gains the reputation of getting up early can sleep late", mood: "wise" },
  { text: "An té a mbíonn an rath ar maidin air bíonn sé air tráthnóna. --  -- He who is lucky in the morning tends to be luck in the evening too", mood: "happy" },
  { text: "An té nach bhfuil láidir ní foláir dó bheith glic. -- He who is not strong has to be clever", mood: "wise" },
  { text: "An té nach mbeireann ar an ngnó beireann an gnó air. -- He who does not get a grip on the job, the job gets a grip on him", mood: "wise" },
  { text: "An té nach nglacann comhairle glacfaidh sé comhrac. -- Whoever will not accept advice must accept strife", mood: "wise" },

  { text: "An té nach trua leis do chás, ná déan do ghearán leis. -- He who does not sympathise with your plight, don't make your complaint to him", mood: "warning" },
{ text: "Ar mhaithe leis féin a níos an cat crónán. -- The cat purrs to please itself", mood: "happy" },
{ text: "Ar scath a chéile a mhaireann na daoine. -- People live in one another's shadow", mood: "wise" },
{ text: "Bailíonn brobh beart. -- A little gathers to a lot", mood: "neutral" },
{ text: "Beart gan leigheas, foighne is fearr dó. -- Patience is the best thing for an incurable situation", mood: "warning" },

{ text: "Beatha teanga í a labhairt. -- It's the life of a language to speak it", mood: "wise" },
{ text: "Beidh lá eile ag an bPaorach. -- Power will have another day", mood: "hopeful" },
{ text: "Bliain le duine agus bliain ina choinne. -- One year with you, one against you", mood: "neutral" },
{ text: "Breithnigh an abhainn sara dtéir ina cuilithe. -- Observe the river before you venture into its currents", mood: "wise" },
{ text: "Briseann an dúchas trí shúile an chait. -- Nature breaks out through the eyes of the cat", mood: "neutral" },
{ text: "Bíonn adharca fada ar na buaibh thar lear. -- Faraway cows have long horns", mood: "neutral" },
{ text: "Bíonn an fhírinne searbh. -- Truth is often bitter ", mood: "warning" },


{ text: "Bíonn blas milis ar phraiseach na gcomharsan. -- The neighbours gruel tastes sweet", mood: "happy" },

{ text: "Bíonn cead cainte ag fear caillte na himeartha. -- The man who has lost the match has permission to talk", mood: "wise" },
{ text: "Bíonn dhá insint ar gach aon scéal. -- There are two sides to every story", mood: "neutral" },
{ text: "Bíonn gach tosú lag. -- Every beginning is weak", mood: "neutral" },
{ text: "Bíonn súil le muir ach ní bhíonn súil le huaigh. -- There is hope of coming back from the sea but none of coming back from the dead", mood: "wise" },
{ text: "Cad a dhéanfadh mac an chait ach luch a mharú. -- Like father like son", mood: "neutral" },
{ text: "Cailín ag Móir is Móir ag iarraidh déirce. -- Mór has a servant girl while she herself is out begging", mood: "humorous" },
{ text: "Caora mhór an t-uan i bhfad. -- The lamb becomes a big heavy sheep over distance", mood: "neutral" },
{ text: "Chonaic mé cheana thú, arsa an cat leis an mbainne te. -- I saw you before, as the cat said to the warm milk...", mood: "humorous" },
{ text: "Ciall agus míchiall - dís ná gabhann le chéile. -- Sense and nonsense - two which do not go together", mood: "wise" },
{ text: "Cuir an breac san eangach sula gcuire tú sa phota é. -- Put the trout in the net before you put it in the pot", mood: "humorous" },
{ text: "Cuir síoda ar ghabhar - is gabhar fós é.-- Put silk on a goat, it's still a goat", mood: "humorous" },
{ text: "D’ordaigh Dia cúnamh. -- God helps those who help themselves", mood: "hopeful" },
{ text: "Doras feasa fiafraí. -- The door to wisdom is to ask questions", mood: "wise" },
{ text: "Dá dhonacht é Séamas ba mheasa bheith ina éagmais. -- However bad Séamas is it would be worse to be without him", mood: "thoughtful" },
{ text: "Dá fhad lá tagann oíche. -- However long the day, night comes", mood: "pensive" },
{ text: "Dá mbeadh soineann go Samhain bheadh breall ar dhuine éigin. -- If it was fine till Halloween someone would be unhappy", mood: "humorous" },
{ text: "Éire i bpáirt, Éire ar lár. -- Ireland divided is Ireland laid low", mood: "patriotic" },
{ text: "Éist le fuaim na habhann agus gheobhair breac. -- Listen to the sound of the river and you will catch a trout", mood: "wise" },
{ text: "Fear na bó faoina heireaball. -- The cows owner must go under her tail", mood: "humorous" },
{ text: "Feileann spallaí do bhallaí chomh maith le clocha móra. -- Small shards suit as well as big stones for building walls", mood: "happy" },
{ text: "Filleann an feall ar an bhfeallaire. -- The evil deed returns to the evildoer", mood: "thoughtful" },
{ text: "Gach dalta mar oiltear. -- Every pupil is as he is trained", mood: "hopeful" },

{ text: "Giorraíonn beirt bóthar. -- Two people shorten the road", mood: "humorous" },
{ text: "Glacann fear críonna comhairle. -- A wise man accepts advice", mood: "wise" },
{ text: "I dtosach na haicíde is fusa í a leigheas.-- It's at the beginning of the disease it is easiest to cure", mood: "thoughtful" },
{ text: "dtus an mhála is ceart a bheith tíosach. -- It's at the beginning of the bag that one must be economical", mood: "practical" },
{ text: "I ndiaidh a chéile a thógtar na caisleáin. -- Rome wasn't built in a day", mood: "hopeful" },
{ text: "Imíonn an tuirse is fanann an tairbhe. -- Tiredness goes away and the benefit remains", mood: "motivational" },
{ text: "Iomad den aithne a mheadaíonn an tarcaisne. -- Familiarity breeds contempt", mood: "wise" },
{ text: "Is ait an mac an saol. -- Life is strange", mood: "happy" },
{ text: "Is beo duine tar éis a bhuailte ach ní beo é tar éis a cháinte. -- A person is alive after being beaten but not after his good name is taken", mood: "philosophical" },
{ text: "Is binn béal ina thost. -- Sweet to hear is a mouth which is silent", mood: "humorous" },
{ text: "Is breá an ní an óige ach ní thagann sí faoi dhó. -- Youth is a fine thing but it does not come twice", mood: "nostalgic" },
{ text: "Is báidhiúil iad lucht aoncheirde. -- Birds of a feather flock together", mood: "admiring" },
{ text: "Is cuma nó muc duine gan seift. -- A shiftless person is the same as a pig", mood: "humorous" },
{ text: "Is deacair ceann críonna a chur ar cholainn óg. -- It's hard to put a wise head on young shoulders", mood: "wise" },
{ text: "Is deacair rogha a bhaint as dhá dhíogha -- It's hard to choose between two evils", mood: "wise" },
{ text: "Is dána gach madra i ndoras a thí féin. -- Every dog is bold in his own doorway", mood: "humorous" },
{ text: "Is dóigh le fear na buile gurb é féin fear na céille. -- The crazy man reckons he is the sensible one", mood: "thoughtful" },
{ text: "Is fada an bóthar nach bhfuil casadh ann. -- It's a long road that has no turning", mood: "neutral" },
{ text: "Is fada siar a théann iarsma an drochbhirt. -- The trail of a bad deed goes a long way", mood: "cautionary" },
{ text: "Is fearr a bheith díomhaoin ná droch-ghnóthach. -- Better to be idle than up to no good", mood: "neutral" },
{ text: "Is fearr an t-imreas ná an t-uaigneas. -- Arguing is better than loneliness", mood: "happy" },
{ text: "Is fearr an tsláinte ná na táinte. -- Health is better than wealth", mood: "happy" },
{ text: "Is fearr beagán den ghaol ná mórán den charthanas. -- A little relationship is better than a lot of charity", mood: "neutral" },
{ text: "Is fearr cara sa chúirt ná punt sa sparán. -- Better a friend in court than a pound in the purse", mood: "neutral" },
{ text: "Is fearr go mall ná go brách. -- Better late than never", mood: "neutral" },
{ text: "Is fearr leath ná meath. -- Half is better than nothing (literally: decaying)", mood: "neutral" },
{ text: "Is fearr lán doirn de cheird ná lán mála d’ór. -- A fistful of a trade is better than a bagful of gold", mood: "neutral" },
{ text: "Is fearr mac le himirt ná mac le hól. --  -- Better to have a son mad for sport than mad for drink", mood: "neutral" },
{ text: "Is fearr marcaíocht ar ghabhar ná coisíocht dá fheabhas. --  -- Better to ride on a goat than the finest walking", mood: "neutral" },
{ text: "Is fearr rith maith ná drochsheasamh. -- A good run is better than a bad stand", mood: "happy" },
{ text: "Is fearr súil le glas ná súil le huaigh. -- Better to look forward to prison than to the grave", mood: "neutral" },
{ text: "Is fearr súil romhat ná dhá shúil i do dhiaidh. -- Better one look before you than two behind", mood: "neutral" },
{ text: "Is furasta fuineadh in aice na béile. -- It's easy to knead next to the mill", mood: "happy" },
{ text: "Is gaire cabhair Dé ná an doras. -- God's help is nearer than the door", mood: "happy" },
{ text: "Is geal gach nua agus is searbh gach gnáth. -- Every novelty is great and every commonplace is bitter", mood: "neutral" },
{ text: "Is geal leis an bhfiach dubh a ghearrcach féin. -- The black raven thinks its own offspring is bright", mood: "happy" },
{ text: "Is geall le scíth malairt oibre. -- A change of work is as good as a rest", mood: "neutral" },
{ text: "Is glas iad na cnoic i bhfad uainn. -- Faraway hills are green", mood: "neutral" },
{ text: "Is iad na muca ciúine a itheann an mhin. -- It's the quiet pigs who eat the meal.", mood: "neutral" },
{ text: "Is in ithe na putóige a bhíonn a tástáil. -- The proof of the pudding is in the eating", mood: "neutral" },
{ text: "Is iomaí cor a chuireann an saol de. -- Life goes through many twists and turns", mood: "wise" },
{ text: "Is leor nod don eolach. -- A nod is enough to the wise", mood: "confident" },
{ text: "Is leor ó Mhór a dícheall. -- All anyone can do is his best", mood: "motivational" },
{ text: "Is lia gach othar i ndiaidh a leighis. -- Every patient is a surgeon after he is cured", mood: "cautionary" },
{ text: "Is lú ná fríd máthair an oilc. -- It takes very little to cause trouble", mood: "humorous" },
{ text: "Is mairg a dheanann deimhin dá dhóchas. -- Woe to he who checks out what he hopes to be true", mood: "thoughtful" },
{ text: "Is mairg a dhéanann an t-olc is a bhíonn bocht ina dhiaidh. -- Woe to the one who does evil and does not profit by it", mood: "cautionary" },
{ text: "Is maith an scáthán súil charad. -- A friend's eye is a good mirror", mood: "wise" },
{ text: "Is maith an scéalaí an aimsir. -- Time will tell", mood: "wise" },
{ text: "Is maith an t-anlann an t-ocras. -- Hunger is a good sauce", mood: "wise" },
{ text: "Is maith an t-iománaí an té a bhíonn ar an gclaí. -- The hurler on the ditch is a great fellow", mood: "motivational" },
{ text: "Is maith le Dia féin cúnamh. -- God himself likes a bit of help", mood: "religious" },
{ text: "Is maol gualainn gan bhráthair. -- A shoulder without a friend is undefended", mood: "humorous" },
{ text: "Is minic a bhris béal duine a shrón. -- It's often a person's mouth broke his nose", mood: "humorous" },
{ text: "Is minic a bhí cú mhall sona. -- It's often a slow hound was content", mood: "happy" },
{ text: "Is minic a gheall tailliúir is ná tiocfadh sé. -- It's often a tailor promised to come and did not", mood: "cautionary" },
{ text: "Is minic ciúin ciontach . -- The quiet ones are often guilty", mood: "thoughtful" },
{ text: "Is mór é luach na foighne. - Patience is worth a lot", mood: "wise" },
{ text: "Is olc an chearc nach scríobann di féin. -- It's a poor hen won't scratch for itself", mood: "humorous" },
{ text: "Is olc an ghaoth nach séideann do dhuine éigin. -- It's an ill wind blows nobody any good", mood: "cautionary" },
{ text: "Is sleamhain an leac ag doras duine uasail. -- The flagstone is slippery at the door of a decent man", mood: "cautionary" },
{ text: "Is treise dúchas ná oiliúint. -- Nature is stronger than training", mood: "wise" },
{ text: "Is trom cearc i bhfad. -- A small burden grows heavier with distance", mood: "humorous" },
{ text: "Is túisce deoch ná scéal. -- A small burden grows heavier with distance", mood: "happy" },
{ text: "Is í an chiall cheannaigh an chiall is fearr. -- Sense bought dearly is the best kind", mood: "wise" },
{ text: "Is í an dias is troime is ísle a chromann a ceann. -- It is the heaviest ear of corn which bows its head lowest", mood: "humorous" },
{ text: "Mair a chapaill is gheobhair féar. -- Live horse and you will get hay", mood: "motivational" },
{ text: "Maireann an chraobh ar an bhfál ach ní mhaireann an lámh a chuir. -- The branch lives on the fence but not the hand that planted it", mood: "wise" },
{ text: "Maireann croí éadrom i bhfad. -- Light heart lives long ", mood: "thoughtful" },
{ text: "Marbh le tae agus marbh gan é. -- Can't live with it, can't live without it", mood: "serious" },
{ text: "Mian mic a shúil. -- A child wants everything he sees", mood: "hopeful" },
{ text: "Mol an óige agus tiocfaidh sí. -- Praise youth and youth will respond", mood: "hopeful" },
{ text: "Mol gort is ná mol geamhar. -- Don't count your chickens before they are hatched", mood: "warning" },
{ text: "Mura gcuirfidh tú san Earrach ní bhainfidh tú sa bhFómhar. -- If you don't sow in Spring you won't reap in Autumn", mood: "warning" },
{ text: "Mura mbeadh agat ach pocán gabhair bí i lár an aonaigh leis. -- Even if you have only a puck goat to sell be in the middle of the fair with it", mood: "humorous" },
{ text: "Más cam díreach an ród is é an bóthar mór an t-aicearra. -- Be it crooked or straight, it's the main road is the shortest way", mood: "wise" },

{ text: "Más olc maol is measa mullach. -- If it's bad on the flat it's worse at the summit", mood: "warning" },
{ text: "Múineann gá seift. -- Necessity teaches resourcefulness", mood: "instructional" },
{ text: "Namhaid an cheird gan í a fhoghlaim. -- If you don't learn your trade, it becomes your enemy", mood: "wise" },
{ text: "Nuair a bheidh do lámh i mbéal na con tarraing go réidh í. -- When your hand is in the hound's mouth withdraw it gently", mood: "instructional" },
{ text: "Nuair a bhíonn an cat amuigh bíonn na lucha ag rince. -- When the cat's away the mice dance", mood: "descriptive" },
{ text: "Nuair is crua don chailleach caithfidh sí rith. -- When it's tough for the hag she has to run", mood: "humorous" },
{ text: "Nuair is gann é an bia is fial é a roinnt. -- When the food is scarce it's generous to share it", mood: "warning" },
{ text: "Ná bac le mac an bhacaigh is ní bhacfaidh mac an bhacaigh leat. -- Mind your own business", mood: "instructional" },
{ text: "Ná cuir do leas ar cairde. -- Don't procrastinate", mood: "instructional" },
{ text: "Ná déan nós is ná bris nós. -- Don't make a custom and don't break a custom", mood: "instructional" },
{ text: "Ná tabhair breith ar an gcéad scéal. -- Hear both sides before judgement", mood: "instructional" },
{ text: "Ní bheathaíonn na breithre na braithre. -- Words alone won't feed the brothers", mood: "wise" },
{ text: "Ní bhfuair minic onóir. -- Familiarity breeds contempt", mood: "disappointed" },
{ text: "Ní bhíonn an rath ach mar a mbíonn an smacht. -- No success without discipline", mood: "wise" },
{ text: "Ní bhíonn fear náireach éadálach. -- A shy man won't be rich", mood: "hopeful" },
{ text: "Ní bhíonn in aon rud ach seal. -- Nothing lasts for ever", mood: "wise" },
{ text: "Ní bhíonn tréan buan. -- The strong don't prevail for ever", mood: "wise" },
{ text: "Ní breac é go raibh sé ar an bport. -- Don't count your fish till it's landed", mood: "humorous" },
{ text: "Ní dhéanfadh an saol capall ráis d’asal.-- The world won't make a racehorse out of a donkey", mood: "wise" },
{ text: "Ní dhéanfaidh smaoineamh an treabhadh duit. -- Thinking will not do the ploughing for you", mood: "serious" },
{ text: "Ní fhaigheann lámh iata ach dorn dúnta. -- A closed hand gets nothing but a closed fist", mood: "serious" },
{ text: "Ní fiú bheith ag seanchas agus an anachain déanta. -- No point in talking when the damage is done", mood: "wise" },
{ text: "Ní féasta go rósta is ní céasta go pósta. -- It's not a feast without a roast and true suffering comes with marriage", mood: "humorous" },
{ text: "Ní féidir bheith ag feadaíl is ag ithe mine. -- You can't whistle and eat meal at the same time", mood: "wise" },
{ text: "Ní féidir leis an ngobadán an dá thrá a fhreastal. -- You can't be two places at once", mood: "humorous" },
{ text: "Ní féidir é a bheith ina ghruth is ina mheadhg agat. -- You can't have it both ways", mood: "wise" },
{ text: "Ní haithne go haontíos. -- You want to know me, come live with me", mood: "serious" },
{ text: "Ní heaspa go díth carad. -- There is no lack so bad as the lack of a friend", mood: "serious" },
{ text: "Ní hé lá na gaoithe lá na scolb. -- The windy day is not the day for thatching", mood: "wise" },
{ text: "Ní ionann dul go tigh an rí agus teacht as. -- It's not the same thing to go to the king's house and to come out of it", mood: "wise" },
{ text: "Ní lia duine ná tuairim. -- People are not more numerous than opinions", mood: "wise" },
{ text: "Ní lia tír ná gnás. -- There are not more countries than there are customs", mood: "wise" },
{ text: "Ní mar a shíltear a bhítear. -- Things aren't always what they seem", mood: "wise" },
{ text: "Ní mhealltar an sionnach faoi dhó. -- You won't fool the fox a second time", mood: "wise" },
{ text: "Ní neart go cur le chéile. -- There is no strength like co-operation", mood: "wise" },
{ text: "Ní sia gob an ghé na gob an ghandail. -- The goose's beak is no longer than the gander's", mood: "humorous" },
{ text: "Ní thagann ciall roimh aois. -- Sense does not come before age", mood: "wise" },
{ text: "Ní théann dlí ar riachtanas. -- Necessity overrides the law", mood: "wise" },
{ text: "Ní troimide an loch an lacha. -- The lake is not heavier for having the duck on it", mood: "wise" },
{ text: "Níl aon tinteán mar do thinteán féin. -- No place like home ", mood: "wise" },
{ text: "Níl leigheas ar an gcathú ach é a mharú le foighne.-- There is no cure for regret but to kill it with patience", mood: "serious" },
{ text: "Níl luibh ná leigheas in aghaidh an bháis. -- There is no herb or cure for death", mood: "serious" },
{ text: "Níl saoi gan locht ná daoi gan tréith. -- There is no wise man without a fault nor any fool without a good feature", mood: "wise" },
{ text: "Níl sprid ná puca nach bhfuil fios a chúise aige. -- There is no spirit nor ghost doesn't know his own business.", mood: "serious" },
{ text: "Níl tuile dá mhéad nach dtránn. -- There is no flood, however great, that does not ebb away", mood: "wise" },
{ text: "Níl íseal ná uasal ach thíos seal agus thuas seal. -- There is neither low not high but down for a while and up for a while.", mood: "wise" },
{ text: "Níor bhris focal maith fiacail riamh. -- A good word never broke a tooth", mood: "wise" },
{ text: "Níor chaill fear an mhisnigh riamh é. -- The man of courage never lost it", mood: "hopeful" },

{ text: "Pós bean ón sliabh agus pósfaidh tú an sliabh ar fad. -- Marry a woman from the mountain and you will marry the entire mountain", mood: "humorous" },
{ text: "Ritheann fear buile trí thuile go dána, ach is minic thug tuile fear buile le fána. -- A crazy man runs through a flood boldly, but it's often a flood swept a crazy man away", mood: "humorous" },
{ text: "Sciúrdann éan as gach ealta. -- A bird flies out of every flock", mood: "humorous" },
{ text: "Seachnaíonn súil an ní ná feiceann. -- An eye disregards what it does not see", mood: "cautionary" },
{ text: "Síoda ar Shiobhán is na preabáin ar a hathair. -- Silk on Siobhán and her father in rags", mood: "humorous" },
{ text: "Súil le breis a chailleann an cearrbhach -- Hoping to beats the odds is what ruins the gambler.", mood: "motivational" },
{ text: "Tabhair rogha don bhodach agus is é an díogha a thoghfaidh sé. -- Give a choice to the churl and it's the worst he will pick", mood: "humorous" },
{ text: "Tagann gach maith le cairde. -- No grace comes singly", mood: "happy" },
{ text: "Taithí a dhéanann máistreacht. -- Practice makes perfect", mood: "wise" },
{ text: "Tar éis a thuigtear gach beart. -- Hindsight is a great thing", mood: "thoughtful" },
{ text: "Tarraingíonn scéal scéal eile. -- One story leads on to another", mood: "cautionary" },
{ text: "Tosach sláinte codladh : deireadh sláinte osna. -- The beginning of health is sleep: the end of health is a sigh", mood: "humorous" },
{ text: "Tuigeann Tadhg Taidhgín. -- Like understands like", mood: "humorous" },
{ text: "Tír gan teanga tír gan anam. -- A country without a language is a country without a soul", mood: "patriotic" },
{ text: "Tús maith leath na hoibre. -- A good start is half the work", mood: "motivational" }
]
